---

# Tested on ansible2.4
# ansible-playbook -i inventory build_and_deploy.yml

- name: BUILD AND DEPLOY CONFIGS
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: "BUILD CONFIG"
      template:
        src: "templates/{{ ansible_network_os }}.j2"
        dest: "./outputs/{{ inventory_hostname }}.cfg"

    - name: "INCLUDE OS CONFIG MODULE"
      include_tasks: "{{ playbook_dir }}/tasks/{{ ansible_network_os }}_config.yml"
